# Generated by tools/gen_tokens.py in ~/dev/patroclus from design.yaml; do not edit.
# patroclus-tokens: begin
patroclus = list(
  light = c(
    bg = "#fbfaf7",
    surface = "#ffffff",
    surface_soft = "#f1ede4",
    text = "#2c2a26",
    headline = "#16140f",
    muted = "#6b665d",
    accent = "#b5612f",
    accent_cool = "#2f6f9f",
    accent_meta = "#9a2233",
    line = "#ddd6c8",
    code_bg = "#f5f1e8"
  ),
  dark = c(
    bg = "#000000",
    surface = "#0b0e12",
    surface_soft = "#13171c",
    text = "#abb2b9",
    headline = "#f2efe9",
    muted = "#8f969d",
    accent = "#cf7d55",
    accent_cool = "#669ac5",
    accent_meta = "#a51c30",
    line = "#2e333b",
    code_bg = "#000000"
  ),
  fonts = c(
    serif = "EB Garamond",
    sans = "IBM Plex Sans",
    mono = "IBM Plex Mono"
  )
)
# patroclus-tokens: end
